<?php

namespace Database\Seeders;

use App\Models\Monster;
use App\Models\Setting;
use Illuminate\Database\Seeder;

/**
 * Seeds beasts for Wild Shape transformation
 *
 * CR limits by druid level:
 * - Level 2: CR 1/4 (no swim/fly)
 * - Level 4: CR 1/2 (no fly)
 * - Level 8: CR 1
 *
 * Moon Circle druids:
 * - Level 2: CR 1
 * - Level 6+: CR = druid level / 3 (rounded down)
 *
 * is_common = true: Available to all druids by default
 * is_common = false: Must be "seen" (unlocked by DM)
 */
class BeastsSeeder extends Seeder
{
    public function run(): void
    {
        $eberron = Setting::where('slug', 'eberron')->first();

        $beasts = $this->getBeasts();

        foreach ($beasts as $beastData) {
            $beast = Monster::updateOrCreate(
                ['slug' => $beastData['slug']],
                $beastData
            );

            if ($eberron) {
                $beast->settings()->syncWithoutDetaching([$eberron->id]);
            }
        }

        $this->command->info('Beasts for Wild Shape seeded: ' . count($beasts));
    }

    private function getBeasts(): array
    {
        return [
            // ==========================================
            // CR 0 — базовые формы (разведка, проникновение)
            // ==========================================
            [
                'slug' => 'cat',
                'name' => ['ru' => 'Кошка'],
                'description' => ['ru' => 'Кошки ценятся за ловкость и острые чувства, особенно ночное зрение.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 2,
                'hit_dice' => '1d4',
                'speed' => ['walk' => 12, 'climb' => 9],
                'abilities' => [
                    'strength' => 3, 'dexterity' => 15, 'constitution' => 10,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3, 'stealth' => 4],
                'senses' => ['darkvision' => '9 м', 'passive_perception' => 13],
                'challenge_rating' => 0,
                'experience_points' => 10,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Кошка совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 0, 'reach' => '1,5 м', 'damage' => '1 рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'rat',
                'name' => ['ru' => 'Крыса'],
                'description' => ['ru' => 'Обычная крыса, обитающая в городах и подземельях. Идеальна для проникновения в узкие щели.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 10,
                'hit_points' => 1,
                'hit_dice' => '1d4-1',
                'speed' => ['walk' => 6],
                'abilities' => [
                    'strength' => 2, 'dexterity' => 11, 'constitution' => 9,
                    'intelligence' => 2, 'wisdom' => 10, 'charisma' => 4,
                ],
                'senses' => ['darkvision' => '9 м', 'passive_perception' => 10],
                'challenge_rating' => 0,
                'experience_points' => 10,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Крыса совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 0, 'reach' => '1,5 м', 'damage' => '1 колющего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'raven',
                'name' => ['ru' => 'Ворон'],
                'description' => ['ru' => 'Умная птица, часто используемая как фамильяр или посланник. Может имитировать звуки.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 1,
                'hit_dice' => '1d4-1',
                'speed' => ['walk' => 3, 'fly' => 15],
                'abilities' => [
                    'strength' => 2, 'dexterity' => 14, 'constitution' => 8,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 6,
                ],
                'skills' => ['perception' => 3],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 0,
                'experience_points' => 10,
                'traits' => [
                    ['name' => 'Подражание', 'description' => 'Ворон может имитировать простые звуки. Существо может распознать имитацию проверкой Мудрости (Проницательность) Сл 10.'],
                ],
                'actions' => [
                    ['name' => 'Клюв', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '1 колющего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => true,
                'is_system' => true,
            ],
            [
                'slug' => 'owl',
                'name' => ['ru' => 'Сова'],
                'description' => ['ru' => 'Ночной хищник с острым зрением и бесшумным полётом. Отличный разведчик.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 1,
                'hit_dice' => '1d4-1',
                'speed' => ['walk' => 1.5, 'fly' => 18],
                'abilities' => [
                    'strength' => 3, 'dexterity' => 13, 'constitution' => 8,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3, 'stealth' => 3],
                'senses' => ['darkvision' => '36 м', 'passive_perception' => 13],
                'challenge_rating' => 0,
                'experience_points' => 10,
                'traits' => [
                    ['name' => 'Пролёт', 'description' => 'Сова не провоцирует атаки, когда вылетает из досягаемости врага.'],
                    ['name' => 'Острый слух и зрение', 'description' => 'Сова совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на слух или зрение.'],
                ],
                'actions' => [
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 3, 'reach' => '1,5 м', 'damage' => '1 рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => true,
                'is_system' => true,
            ],
            [
                'slug' => 'spider',
                'name' => ['ru' => 'Паук'],
                'description' => ['ru' => 'Маленький паук, плетущий сети. Может лазать по любым поверхностям.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 1,
                'hit_dice' => '1d4-1',
                'speed' => ['walk' => 6, 'climb' => 6],
                'abilities' => [
                    'strength' => 2, 'dexterity' => 14, 'constitution' => 8,
                    'intelligence' => 1, 'wisdom' => 10, 'charisma' => 2,
                ],
                'skills' => ['stealth' => 4],
                'senses' => ['darkvision' => '9 м', 'passive_perception' => 10],
                'challenge_rating' => 0,
                'experience_points' => 10,
                'traits' => [
                    ['name' => 'Паучье лазание', 'description' => 'Паук может лазать по сложным поверхностям, включая потолки, без проверки характеристик.'],
                    ['name' => 'Чувство паутины', 'description' => 'Находясь в контакте с паутиной, паук знает точное местоположение всех существ, касающихся той же паутины.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '1 колющего урона + СП Тел Сл 9, иначе 2 (1d4) урона ядом'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'badger',
                'name' => ['ru' => 'Барсук'],
                'description' => ['ru' => 'Небольшое, но агрессивное животное, живущее в норах.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 10,
                'hit_points' => 3,
                'hit_dice' => '1d4+1',
                'speed' => ['walk' => 6, 'burrow' => 1.5],
                'abilities' => [
                    'strength' => 4, 'dexterity' => 11, 'constitution' => 12,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 5,
                ],
                'senses' => ['darkvision' => '9 м', 'passive_perception' => 11],
                'challenge_rating' => 0,
                'experience_points' => 10,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Барсук совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 2, 'reach' => '1,5 м', 'damage' => '1 колющего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'frog',
                'name' => ['ru' => 'Лягушка'],
                'description' => ['ru' => 'Маленькое земноводное, обитающее у водоёмов. Может дышать под водой.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 1,
                'hit_dice' => '1d4-1',
                'speed' => ['walk' => 6, 'swim' => 6],
                'abilities' => [
                    'strength' => 1, 'dexterity' => 13, 'constitution' => 8,
                    'intelligence' => 1, 'wisdom' => 8, 'charisma' => 3,
                ],
                'skills' => ['perception' => 1, 'stealth' => 3],
                'senses' => ['darkvision' => '9 м', 'passive_perception' => 11],
                'challenge_rating' => 0,
                'experience_points' => 0,
                'traits' => [
                    ['name' => 'Амфибия', 'description' => 'Лягушка может дышать воздухом и под водой.'],
                    ['name' => 'Прыжок с места', 'description' => 'Прыжок лягушки в длину составляет 3 м, а в высоту — 1,5 м.'],
                ],
                'actions' => [],
                'is_common' => true,
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],

            // ==========================================
            // CR 1/8 — мелкие хищники
            // ==========================================
            [
                'slug' => 'mastiff',
                'name' => ['ru' => 'Мастиф'],
                'description' => ['ru' => 'Крупная сторожевая собака, верная и свирепая.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 5,
                'hit_dice' => '1d8+1',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 13, 'dexterity' => 14, 'constitution' => 12,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 0.125,
                'experience_points' => 25,
                'traits' => [
                    ['name' => 'Острый слух и обоняние', 'description' => 'Мастиф совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на слух или обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 3, 'reach' => '1,5 м', 'damage' => '4 (1d6+1) колющего урона. СП Сил Сл 11, иначе цель сбита с ног.'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'poisonous-snake',
                'name' => ['ru' => 'Ядовитая змея'],
                'description' => ['ru' => 'Небольшая ядовитая змея, опасная для неосторожных.'],
                'size' => 'tiny',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 13,
                'hit_points' => 2,
                'hit_dice' => '1d4',
                'speed' => ['walk' => 9, 'swim' => 9],
                'abilities' => [
                    'strength' => 2, 'dexterity' => 16, 'constitution' => 11,
                    'intelligence' => 1, 'wisdom' => 10, 'charisma' => 3,
                ],
                'senses' => ['blindsight' => '3 м', 'passive_perception' => 10],
                'challenge_rating' => 0.125,
                'experience_points' => 25,
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '1 колющего урона + СП Тел Сл 10, иначе 5 (2d4) урона ядом (половина при успехе)'],
                ],
                'is_common' => true,
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-rat',
                'name' => ['ru' => 'Гигантская крыса'],
                'description' => ['ru' => 'Крыса размером с собаку, обитающая в подземельях и канализации.'],
                'size' => 'small',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 7,
                'hit_dice' => '2d6',
                'speed' => ['walk' => 9],
                'abilities' => [
                    'strength' => 7, 'dexterity' => 15, 'constitution' => 11,
                    'intelligence' => 2, 'wisdom' => 10, 'charisma' => 4,
                ],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 10],
                'challenge_rating' => 0.125,
                'experience_points' => 25,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Крыса совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                    ['name' => 'Тактика стаи', 'description' => 'Крыса совершает с преимуществом атаки, если рядом с целью есть союзник.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '4 (1d4+2) колющего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],

            // ==========================================
            // CR 1/4 — первые боевые формы (уровень 2)
            // ==========================================
            [
                'slug' => 'wolf',
                'name' => ['ru' => 'Волк'],
                'description' => ['ru' => 'Умный хищник, охотящийся стаями. Классическая боевая форма друида.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 13,
                'hit_points' => 11,
                'hit_dice' => '2d8+2',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 12, 'dexterity' => 15, 'constitution' => 12,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 6,
                ],
                'skills' => ['perception' => 3, 'stealth' => 4],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'traits' => [
                    ['name' => 'Острый слух и обоняние', 'description' => 'Волк совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на слух или обоняние.'],
                    ['name' => 'Тактика стаи', 'description' => 'Волк совершает с преимуществом атаки, если рядом с целью есть союзник.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '7 (2d4+2) колющего урона. СП Сил Сл 11, иначе цель сбита с ног.'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'boar',
                'name' => ['ru' => 'Кабан'],
                'description' => ['ru' => 'Дикий кабан с острыми клыками, агрессивный когда загнан в угол.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 11,
                'hit_dice' => '2d8+2',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 13, 'dexterity' => 11, 'constitution' => 12,
                    'intelligence' => 2, 'wisdom' => 9, 'charisma' => 5,
                ],
                'senses' => ['passive_perception' => 9],
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'traits' => [
                    ['name' => 'Атака с разбега', 'description' => 'Если кабан переместится минимум на 6 м к цели и попадёт клыками, цель получает +3 (1d6) урона. СП Сил Сл 11, иначе сбита с ног.'],
                    ['name' => 'Безжалостность', 'description' => 'При падении до 0 HP (если не убит сразу) — СП Тел Сл 10, при успехе остаётся 1 HP.'],
                ],
                'actions' => [
                    ['name' => 'Клыки', 'type' => 'melee', 'attack_bonus' => 3, 'reach' => '1,5 м', 'damage' => '4 (1d6+1) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'panther',
                'name' => ['ru' => 'Пантера'],
                'description' => ['ru' => 'Грациозная и смертоносная большая кошка, мастер засад.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 13,
                'hit_dice' => '3d8',
                'speed' => ['walk' => 15, 'climb' => 12],
                'abilities' => [
                    'strength' => 14, 'dexterity' => 15, 'constitution' => 10,
                    'intelligence' => 3, 'wisdom' => 14, 'charisma' => 7,
                ],
                'skills' => ['perception' => 4, 'stealth' => 6],
                'senses' => ['passive_perception' => 14],
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Пантера совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                    ['name' => 'Прыжок', 'description' => 'Если пантера переместится минимум на 6 м и попадёт когтями, цель должна СП Сил Сл 12 или сбита с ног. Если сбита — бонусная атака укусом.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '5 (1d6+2) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '4 (1d4+2) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'elk',
                'name' => ['ru' => 'Лось'],
                'description' => ['ru' => 'Величественный лесной зверь с могучими рогами. Хорош для передвижения.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 10,
                'hit_points' => 13,
                'hit_dice' => '2d10+2',
                'speed' => ['walk' => 15],
                'abilities' => [
                    'strength' => 16, 'dexterity' => 10, 'constitution' => 12,
                    'intelligence' => 2, 'wisdom' => 10, 'charisma' => 6,
                ],
                'senses' => ['passive_perception' => 10],
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'traits' => [
                    ['name' => 'Атака с разбега', 'description' => 'Если лось переместится минимум на 6 м и попадёт рогами, цель получает +7 (2d6) урона. СП Сил Сл 13, иначе сбита с ног.'],
                ],
                'actions' => [
                    ['name' => 'Рога', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '6 (1d6+3) дробящего урона'],
                    ['name' => 'Копыта', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '8 (2d4+3) дробящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-badger',
                'name' => ['ru' => 'Гигантский барсук'],
                'description' => ['ru' => 'Огромный и свирепый барсук, способный прорывать туннели.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 10,
                'hit_points' => 13,
                'hit_dice' => '2d8+4',
                'speed' => ['walk' => 9, 'burrow' => 3],
                'abilities' => [
                    'strength' => 13, 'dexterity' => 10, 'constitution' => 15,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 5,
                ],
                'senses' => ['darkvision' => '9 м', 'passive_perception' => 11],
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Барсук совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Барсук совершает две атаки: укус и когти.'],
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 3, 'reach' => '1,5 м', 'damage' => '4 (1d6+1) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 3, 'reach' => '1,5 м', 'damage' => '6 (2d4+1) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-frog',
                'name' => ['ru' => 'Гигантская лягушка'],
                'description' => ['ru' => 'Огромная амфибия, способная проглотить добычу целиком.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 18,
                'hit_dice' => '4d8',
                'speed' => ['walk' => 9, 'swim' => 9],
                'abilities' => [
                    'strength' => 12, 'dexterity' => 13, 'constitution' => 11,
                    'intelligence' => 2, 'wisdom' => 10, 'charisma' => 3,
                ],
                'skills' => ['perception' => 2, 'stealth' => 3],
                'senses' => ['darkvision' => '9 м', 'passive_perception' => 12],
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'traits' => [
                    ['name' => 'Амфибия', 'description' => 'Лягушка может дышать воздухом и под водой.'],
                    ['name' => 'Прыжок с места', 'description' => 'Прыжок в длину 6 м, в высоту 3 м.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 3, 'reach' => '1,5 м', 'damage' => '4 (1d6+1) колющего, цель схвачена (Сл 11). Пока схвачена — опутана.'],
                    ['name' => 'Проглатывание', 'description' => 'Атака укусом по Маленькой или меньше схваченной цели. При попадании цель проглочена: ослеплена, опутана, 5 (2d4) урона кислотой в начале хода.'],
                ],
                'is_common' => true,
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-wolf-spider',
                'name' => ['ru' => 'Гигантский паук-волк'],
                'description' => ['ru' => 'Огромный охотящийся паук, не плетущий паутину. Быстрый и ядовитый.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 13,
                'hit_points' => 11,
                'hit_dice' => '2d8+2',
                'speed' => ['walk' => 12, 'climb' => 12],
                'abilities' => [
                    'strength' => 12, 'dexterity' => 16, 'constitution' => 13,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 4,
                ],
                'skills' => ['perception' => 3, 'stealth' => 7],
                'senses' => ['blindsight' => '3 м', 'darkvision' => '18 м', 'passive_perception' => 13],
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'traits' => [
                    ['name' => 'Паучье лазание', 'description' => 'Паук может лазать по сложным поверхностям, включая потолки.'],
                    ['name' => 'Чувство паутины', 'description' => 'Паук знает местоположение существ, касающихся той же паутины.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 3, 'reach' => '1,5 м', 'damage' => '4 (1d6+1) колющего. СП Тел Сл 11, иначе 7 (2d6) урона ядом (половина при успехе). При провале на 5+ — парализован на 1 час.'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],

            // ==========================================
            // CR 1/2 — средние боевые формы (уровень 4)
            // ==========================================
            [
                'slug' => 'black-bear',
                'name' => ['ru' => 'Чёрный медведь'],
                'description' => ['ru' => 'Медведь средних размеров, обитающий в лесах. Надёжная боевая форма.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 19,
                'hit_dice' => '3d8+6',
                'speed' => ['walk' => 12, 'climb' => 9],
                'abilities' => [
                    'strength' => 15, 'dexterity' => 10, 'constitution' => 14,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 0.5,
                'experience_points' => 100,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Медведь совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Медведь совершает две атаки: укус и когти.'],
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '5 (1d6+2) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '7 (2d4+2) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'ape',
                'name' => ['ru' => 'Обезьяна'],
                'description' => ['ru' => 'Крупная человекообразная обезьяна с мощными руками. Может бросать предметы.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 19,
                'hit_dice' => '3d8+6',
                'speed' => ['walk' => 9, 'climb' => 9],
                'abilities' => [
                    'strength' => 16, 'dexterity' => 14, 'constitution' => 14,
                    'intelligence' => 6, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['athletics' => 5, 'perception' => 3],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 0.5,
                'experience_points' => 100,
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Обезьяна совершает две атаки кулаками.'],
                    ['name' => 'Кулак', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '6 (1d6+3) дробящего урона'],
                    ['name' => 'Камень', 'type' => 'ranged', 'attack_bonus' => 5, 'range' => '7,5/15 м', 'damage' => '6 (1d6+3) дробящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'crocodile',
                'name' => ['ru' => 'Крокодил'],
                'description' => ['ru' => 'Смертоносный водный хищник с мощными челюстями.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 19,
                'hit_dice' => '3d10+3',
                'speed' => ['walk' => 6, 'swim' => 9],
                'abilities' => [
                    'strength' => 15, 'dexterity' => 10, 'constitution' => 13,
                    'intelligence' => 2, 'wisdom' => 10, 'charisma' => 5,
                ],
                'skills' => ['stealth' => 2],
                'senses' => ['passive_perception' => 10],
                'challenge_rating' => 0.5,
                'experience_points' => 100,
                'traits' => [
                    ['name' => 'Задержка дыхания', 'description' => 'Крокодил может задерживать дыхание на 15 минут.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '7 (1d10+2) колющего урона. Цель схвачена (Сл 12), опутана, крокодил не может кусать других.'],
                ],
                'is_common' => true,
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'warhorse',
                'name' => ['ru' => 'Боевой конь'],
                'description' => ['ru' => 'Обученный боевой скакун. Быстрый и мощный.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 19,
                'hit_dice' => '3d10+3',
                'speed' => ['walk' => 18],
                'abilities' => [
                    'strength' => 18, 'dexterity' => 12, 'constitution' => 13,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 7,
                ],
                'senses' => ['passive_perception' => 11],
                'challenge_rating' => 0.5,
                'experience_points' => 100,
                'traits' => [
                    ['name' => 'Растаптывание', 'description' => 'Если конь переместится минимум на 6 м к цели и попадёт копытами, цель должна СП Сил Сл 14 или сбита с ног. Если сбита — бонусная атака копытами.'],
                ],
                'actions' => [
                    ['name' => 'Копыта', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '11 (2d6+4) дробящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],

            // ==========================================
            // CR 1 — сильные боевые формы (уровень 8 / Луна уровень 2)
            // ==========================================
            [
                'slug' => 'brown-bear',
                'name' => ['ru' => 'Бурый медведь'],
                'description' => ['ru' => 'Крупный и мощный медведь. Одна из лучших боевых форм для обычного друида.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 34,
                'hit_dice' => '4d10+12',
                'speed' => ['walk' => 12, 'climb' => 9],
                'abilities' => [
                    'strength' => 19, 'dexterity' => 10, 'constitution' => 16,
                    'intelligence' => 2, 'wisdom' => 13, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 1,
                'experience_points' => 200,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Медведь совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Медведь совершает две атаки: укус и когти.'],
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '8 (1d8+4) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '11 (2d6+4) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'dire-wolf',
                'name' => ['ru' => 'Лютоволк'],
                'description' => ['ru' => 'Огромный и свирепый волк. Высокий КД и тактика стаи.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 14,
                'hit_points' => 37,
                'hit_dice' => '5d10+10',
                'speed' => ['walk' => 15],
                'abilities' => [
                    'strength' => 17, 'dexterity' => 15, 'constitution' => 15,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3, 'stealth' => 4],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 1,
                'experience_points' => 200,
                'traits' => [
                    ['name' => 'Острый слух и обоняние', 'description' => 'Волк совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на слух или обоняние.'],
                    ['name' => 'Тактика стаи', 'description' => 'Волк совершает с преимуществом атаки, если рядом с целью есть союзник.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '10 (2d6+3) колющего урона. СП Сил Сл 13, иначе цель сбита с ног.'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'lion',
                'name' => ['ru' => 'Лев'],
                'description' => ['ru' => 'Величественный хищник саванн. Охотится группами.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 26,
                'hit_dice' => '4d10+4',
                'speed' => ['walk' => 15],
                'abilities' => [
                    'strength' => 17, 'dexterity' => 15, 'constitution' => 13,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 8,
                ],
                'skills' => ['perception' => 3, 'stealth' => 6],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 1,
                'experience_points' => 200,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Лев совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                    ['name' => 'Тактика стаи', 'description' => 'Лев совершает с преимуществом атаки, если рядом с целью есть союзник.'],
                    ['name' => 'Прыжок', 'description' => 'Если лев переместится минимум на 6 м и попадёт когтями, цель СП Сил Сл 13 или сбита с ног. Если сбита — бонусная атака укусом.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '7 (1d8+3) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '6 (1d6+3) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'tiger',
                'name' => ['ru' => 'Тигр'],
                'description' => ['ru' => 'Смертоносный полосатый хищник джунглей. Высокий урон.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 37,
                'hit_dice' => '5d10+10',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 17, 'dexterity' => 15, 'constitution' => 14,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 8,
                ],
                'skills' => ['perception' => 3, 'stealth' => 6],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 13],
                'challenge_rating' => 1,
                'experience_points' => 200,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Тигр совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                    ['name' => 'Прыжок', 'description' => 'Если тигр переместится минимум на 6 м и попадёт когтями, цель СП Сил Сл 13 или сбита с ног. Если сбита — бонусная атака укусом.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '8 (1d10+3) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '7 (1d8+3) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-spider',
                'name' => ['ru' => 'Гигантский паук'],
                'description' => ['ru' => 'Огромный паук, плетущий сети. Ядовитый укус и паутина.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 14,
                'hit_points' => 26,
                'hit_dice' => '4d10+4',
                'speed' => ['walk' => 9, 'climb' => 9],
                'abilities' => [
                    'strength' => 14, 'dexterity' => 16, 'constitution' => 12,
                    'intelligence' => 2, 'wisdom' => 11, 'charisma' => 4,
                ],
                'skills' => ['stealth' => 7],
                'senses' => ['blindsight' => '3 м', 'darkvision' => '18 м', 'passive_perception' => 10],
                'challenge_rating' => 1,
                'experience_points' => 200,
                'traits' => [
                    ['name' => 'Паучье лазание', 'description' => 'Паук может лазать по сложным поверхностям, включая потолки.'],
                    ['name' => 'Чувство паутины', 'description' => 'Паук знает местоположение существ, касающихся его паутины.'],
                    ['name' => 'Хождение по паутине', 'description' => 'Паук игнорирует ограничения движения от паутины.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '7 (1d8+3) колющего. СП Тел Сл 11, иначе 9 (2d8) урона ядом (половина при успехе). При провале на 5+ — парализован на 1 час.'],
                    ['name' => 'Паутина', 'type' => 'ranged', 'attack_bonus' => 5, 'range' => '9/18 м', 'damage' => 'Цель опутана. Высвобождение: СП Сил Сл 12 или атака по паутине (КД 10, 5 HP, иммунитет к яду и психическому).'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-eagle',
                'name' => ['ru' => 'Гигантский орёл'],
                'description' => ['ru' => 'Огромная благородная птица с размахом крыльев более 6 метров. Разумна и понимает речь.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'нейтральный добрый',
                'armor_class' => 13,
                'hit_points' => 26,
                'hit_dice' => '4d10+4',
                'speed' => ['walk' => 3, 'fly' => 24],
                'abilities' => [
                    'strength' => 16, 'dexterity' => 17, 'constitution' => 13,
                    'intelligence' => 8, 'wisdom' => 14, 'charisma' => 10,
                ],
                'skills' => ['perception' => 4],
                'senses' => ['passive_perception' => 14],
                'languages' => ['Гигантский орлиный', 'понимает Общий и Ауран'],
                'challenge_rating' => 1,
                'experience_points' => 200,
                'traits' => [
                    ['name' => 'Острое зрение', 'description' => 'Орёл совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на зрение.'],
                ],
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Орёл совершает две атаки: клюв и когти.'],
                    ['name' => 'Клюв', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '6 (1d6+3) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '10 (2d6+3) рубящего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => true,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-hyena',
                'name' => ['ru' => 'Гигантская гиена'],
                'description' => ['ru' => 'Огромная гиена-падальщик. Агрессивна и безжалостна.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 45,
                'hit_dice' => '6d10+12',
                'speed' => ['walk' => 15],
                'abilities' => [
                    'strength' => 16, 'dexterity' => 14, 'constitution' => 14,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 1,
                'experience_points' => 200,
                'traits' => [
                    ['name' => 'Безжалостность', 'description' => 'При падении до 0 HP — СП Тел Сл 10, при успехе остаётся 1 HP.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '10 (2d6+3) колющего урона'],
                ],
                'is_common' => true,
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],

            // ==========================================
            // CR 2 — мощные формы (Круг Луны уровень 6)
            // ==========================================
            [
                'slug' => 'giant-boar',
                'name' => ['ru' => 'Гигантский кабан'],
                'description' => ['ru' => 'Массивный свирепый кабан с огромными клыками.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 42,
                'hit_dice' => '5d10+15',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 17, 'dexterity' => 10, 'constitution' => 16,
                    'intelligence' => 2, 'wisdom' => 7, 'charisma' => 5,
                ],
                'senses' => ['passive_perception' => 8],
                'challenge_rating' => 2,
                'experience_points' => 450,
                'traits' => [
                    ['name' => 'Атака с разбега', 'description' => 'Если кабан переместится минимум на 6 м и попадёт клыками, цель получает +7 (2d6) урона. СП Сил Сл 13, иначе сбита с ног.'],
                    ['name' => 'Безжалостность', 'description' => 'При падении до 0 HP — СП Тел Сл 10, при успехе остаётся 1 HP.'],
                ],
                'actions' => [
                    ['name' => 'Клыки', 'type' => 'melee', 'attack_bonus' => 5, 'reach' => '1,5 м', 'damage' => '10 (2d6+3) рубящего урона'],
                ],
                'is_common' => false, // редкий
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'polar-bear',
                'name' => ['ru' => 'Белый медведь'],
                'description' => ['ru' => 'Огромный хищник арктических земель. Один из сильнейших медведей.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 42,
                'hit_dice' => '5d10+15',
                'speed' => ['walk' => 12, 'swim' => 9],
                'abilities' => [
                    'strength' => 20, 'dexterity' => 10, 'constitution' => 16,
                    'intelligence' => 2, 'wisdom' => 13, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 2,
                'experience_points' => 450,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Медведь совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                ],
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Медведь совершает две атаки: укус и когти.'],
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 7, 'reach' => '1,5 м', 'damage' => '9 (1d8+5) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 7, 'reach' => '1,5 м', 'damage' => '12 (2d6+5) рубящего урона'],
                ],
                'is_common' => false, // редкий (арктика)
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'saber-toothed-tiger',
                'name' => ['ru' => 'Саблезубый тигр'],
                'description' => ['ru' => 'Древний хищник с огромными клыками. Очень высокий урон.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 52,
                'hit_dice' => '7d10+14',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 18, 'dexterity' => 14, 'constitution' => 15,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 8,
                ],
                'skills' => ['perception' => 3, 'stealth' => 6],
                'senses' => ['passive_perception' => 13],
                'challenge_rating' => 2,
                'experience_points' => 450,
                'traits' => [
                    ['name' => 'Острое обоняние', 'description' => 'Тигр совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.'],
                    ['name' => 'Прыжок', 'description' => 'Если тигр переместится минимум на 6 м и попадёт когтями, цель СП Сил Сл 14 или сбита с ног. Если сбита — бонусная атака укусом.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '10 (1d10+5) колющего урона'],
                    ['name' => 'Когти', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '12 (2d6+5) рубящего урона'],
                ],
                'is_common' => false, // редкий (доисторический)
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-constrictor-snake',
                'name' => ['ru' => 'Гигантский удав'],
                'description' => ['ru' => 'Огромная змея, убивающая добычу удушением. Достигает 9 метров в длину.'],
                'size' => 'huge',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 60,
                'hit_dice' => '8d12+8',
                'speed' => ['walk' => 9, 'swim' => 9],
                'abilities' => [
                    'strength' => 19, 'dexterity' => 14, 'constitution' => 12,
                    'intelligence' => 1, 'wisdom' => 10, 'charisma' => 3,
                ],
                'skills' => ['perception' => 2],
                'senses' => ['blindsight' => '3 м', 'passive_perception' => 12],
                'challenge_rating' => 2,
                'experience_points' => 450,
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '3 м', 'damage' => '11 (2d6+4) колющего урона'],
                    ['name' => 'Сдавливание', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '13 (2d8+4) дробящего. Цель схвачена (Сл 16), опутана. Удав не может сдавливать других.'],
                ],
                'is_common' => false, // редкий (джунгли)
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-elk',
                'name' => ['ru' => 'Гигантский лось'],
                'description' => ['ru' => 'Огромный величественный лось. Часто служит ездовым животным для эльфов.'],
                'size' => 'huge',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 14,
                'hit_points' => 42,
                'hit_dice' => '5d12+10',
                'speed' => ['walk' => 18],
                'abilities' => [
                    'strength' => 19, 'dexterity' => 16, 'constitution' => 14,
                    'intelligence' => 7, 'wisdom' => 14, 'charisma' => 10,
                ],
                'skills' => ['perception' => 4],
                'senses' => ['passive_perception' => 14],
                'languages' => ['Гигантский лосиный', 'понимает Общий, Эльфийский и Сильван'],
                'challenge_rating' => 2,
                'experience_points' => 450,
                'traits' => [
                    ['name' => 'Атака с разбега', 'description' => 'Если лось переместится минимум на 6 м и попадёт рогами, цель получает +7 (2d6) урона. СП Сил Сл 14, иначе сбита с ног.'],
                ],
                'actions' => [
                    ['name' => 'Рога', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '3 м', 'damage' => '11 (2d6+4) дробящего урона'],
                    ['name' => 'Копыта', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '22 (4d8+4) дробящего урона'],
                ],
                'is_common' => false, // редкий (фейские леса)
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'rhinoceros',
                'name' => ['ru' => 'Носорог'],
                'description' => ['ru' => 'Массивное травоядное с мощным рогом. Опасен при атаке с разбега.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 11,
                'hit_points' => 45,
                'hit_dice' => '6d10+12',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 21, 'dexterity' => 8, 'constitution' => 15,
                    'intelligence' => 2, 'wisdom' => 12, 'charisma' => 6,
                ],
                'senses' => ['passive_perception' => 11],
                'challenge_rating' => 2,
                'experience_points' => 450,
                'traits' => [
                    ['name' => 'Атака с разбега', 'description' => 'Если носорог переместится минимум на 6 м и попадёт атакой, цель получает +9 (2d8) урона. СП Сил Сл 15, иначе сбита с ног.'],
                ],
                'actions' => [
                    ['name' => 'Рог', 'type' => 'melee', 'attack_bonus' => 7, 'reach' => '1,5 м', 'damage' => '14 (2d8+5) дробящего урона'],
                ],
                'is_common' => false, // редкий (саванна)
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],

            // ==========================================
            // CR 3+ — элитные формы (Круг Луны высокий уровень)
            // ==========================================
            [
                'slug' => 'giant-scorpion',
                'name' => ['ru' => 'Гигантский скорпион'],
                'description' => ['ru' => 'Огромный скорпион с мощными клешнями и ядовитым жалом.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 15,
                'hit_points' => 52,
                'hit_dice' => '7d10+14',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 15, 'dexterity' => 13, 'constitution' => 15,
                    'intelligence' => 1, 'wisdom' => 9, 'charisma' => 3,
                ],
                'senses' => ['blindsight' => '18 м', 'passive_perception' => 9],
                'challenge_rating' => 3,
                'experience_points' => 700,
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Скорпион совершает три атаки: две клешнями и одну жалом.'],
                    ['name' => 'Клешня', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '6 (1d8+2) дробящего. Цель схвачена (Сл 12). Скорпион имеет две клешни.'],
                    ['name' => 'Жало', 'type' => 'melee', 'attack_bonus' => 4, 'reach' => '1,5 м', 'damage' => '7 (1d10+2) колющего + СП Тел Сл 12, иначе 22 (4d10) урона ядом (половина при успехе).'],
                ],
                'is_common' => false, // редкий (пустыни)
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'killer-whale',
                'name' => ['ru' => 'Косатка'],
                'description' => ['ru' => 'Огромный морской хищник. Охотится стаями и очень умна.'],
                'size' => 'huge',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 12,
                'hit_points' => 90,
                'hit_dice' => '12d12+12',
                'speed' => ['walk' => 0, 'swim' => 18],
                'abilities' => [
                    'strength' => 19, 'dexterity' => 10, 'constitution' => 13,
                    'intelligence' => 3, 'wisdom' => 12, 'charisma' => 7,
                ],
                'skills' => ['perception' => 3],
                'senses' => ['blindsight' => '36 м', 'passive_perception' => 13],
                'challenge_rating' => 3,
                'experience_points' => 700,
                'traits' => [
                    ['name' => 'Эхолокация', 'description' => 'Косатка не может использовать слепое зрение, если оглушена.'],
                    ['name' => 'Задержка дыхания', 'description' => 'Косатка может задерживать дыхание на 30 минут.'],
                    ['name' => 'Острый слух', 'description' => 'Косатка совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на слух.'],
                ],
                'actions' => [
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 6, 'reach' => '1,5 м', 'damage' => '21 (5d6+4) колющего урона'],
                ],
                'is_common' => false, // редкий (океан)
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'giant-crocodile',
                'name' => ['ru' => 'Гигантский крокодил'],
                'description' => ['ru' => 'Огромный доисторический крокодил длиной до 9 метров.'],
                'size' => 'huge',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 14,
                'hit_points' => 85,
                'hit_dice' => '9d12+27',
                'speed' => ['walk' => 9, 'swim' => 15],
                'abilities' => [
                    'strength' => 21, 'dexterity' => 9, 'constitution' => 17,
                    'intelligence' => 2, 'wisdom' => 10, 'charisma' => 7,
                ],
                'skills' => ['stealth' => 5],
                'senses' => ['passive_perception' => 10],
                'challenge_rating' => 5,
                'experience_points' => 1800,
                'traits' => [
                    ['name' => 'Задержка дыхания', 'description' => 'Крокодил может задерживать дыхание на 30 минут.'],
                ],
                'actions' => [
                    ['name' => 'Мультиатака', 'description' => 'Крокодил совершает две атаки: укус и хвост.'],
                    ['name' => 'Укус', 'type' => 'melee', 'attack_bonus' => 8, 'reach' => '1,5 м', 'damage' => '21 (3d10+5) колющего. Цель схвачена (Сл 16), опутана. Крокодил не может кусать других, пока держит.'],
                    ['name' => 'Хвост', 'type' => 'melee', 'attack_bonus' => 8, 'reach' => '3 м', 'damage' => '14 (2d8+5) дробящего. СП Сил Сл 16, иначе сбита с ног. Только по не схваченным целям.'],
                ],
                'is_common' => false, // редкий (тропики)
                'has_swim' => true,
                'has_fly' => false,
                'is_system' => true,
            ],
            [
                'slug' => 'mammoth',
                'name' => ['ru' => 'Мамонт'],
                'description' => ['ru' => 'Гигантский доисторический слон с огромными бивнями и густой шерстью.'],
                'size' => 'huge',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 13,
                'hit_points' => 126,
                'hit_dice' => '11d12+55',
                'speed' => ['walk' => 12],
                'abilities' => [
                    'strength' => 24, 'dexterity' => 9, 'constitution' => 21,
                    'intelligence' => 3, 'wisdom' => 11, 'charisma' => 6,
                ],
                'senses' => ['passive_perception' => 10],
                'challenge_rating' => 6,
                'experience_points' => 2300,
                'traits' => [
                    ['name' => 'Растаптывание', 'description' => 'Если мамонт переместится минимум на 6 м и попадёт бивнями, цель СП Сил Сл 18 или сбита с ног. Если сбита — бонусная атака растаптыванием.'],
                ],
                'actions' => [
                    ['name' => 'Бивни', 'type' => 'melee', 'attack_bonus' => 10, 'reach' => '3 м', 'damage' => '25 (4d8+7) колющего урона'],
                    ['name' => 'Растаптывание', 'type' => 'melee', 'attack_bonus' => 10, 'reach' => '1,5 м', 'damage' => '29 (4d10+7) дробящего. Только по сбитым с ног целям.'],
                ],
                'is_common' => false, // редкий (арктика/доисторический)
                'has_swim' => false,
                'has_fly' => false,
                'is_system' => true,
            ],
        ];
    }
}
