<?php

namespace Database\Seeders;

use App\Models\Monster;
use App\Models\Setting;
use Illuminate\Database\Seeder;

class MonstersSeeder extends Seeder
{
    public function run(): void
    {
        $eberron = Setting::where('slug', 'eberron')->first();
        $forgottenRealms = Setting::where('slug', 'forgotten-realms')->first();

        // Core SRD monsters (available in all settings)
        $monsters = $this->getMonsters();

        foreach ($monsters as $monsterData) {
            $monster = Monster::updateOrCreate(
                ['slug' => $monsterData['slug']],
                $monsterData
            );

            // Attach to all available settings
            $settingIds = [];
            if ($eberron) {
                $settingIds[] = $eberron->id;
            }
            if ($forgottenRealms) {
                $settingIds[] = $forgottenRealms->id;
            }

            if (!empty($settingIds)) {
                $monster->settings()->syncWithoutDetaching($settingIds);
            }
        }

        $this->command->info('Monsters seeded successfully: ' . count($monsters) . ' creatures.');
    }

    private function getMonsters(): array
    {
        return [
            // ==========================================
            // LOW CR (0 - 1/2)
            // ==========================================

            // KOBOLD (CR 1/8)
            [
                'slug' => 'kobold',
                'name' => ['ru' => 'Кобольд'],
                'description' => ['ru' => 'Кобольды — маленькие рептилоидные гуманоиды с чешуйчатой кожей, варьирующейся от тёмно-коричневого до чёрного цвета. Они живут в тёмных местах, обычно в подземных логовах, и ненавидят солнечный свет.'],
                'size' => 'small',
                'type' => 'humanoid',
                'alignment' => 'законно-злой',
                'armor_class' => 12,
                'armor_type' => null,
                'hit_points' => 5,
                'hit_dice' => '2d6-2',
                'challenge_rating' => 0.125,
                'experience_points' => 25,
                'abilities' => [
                    'strength' => 7,
                    'dexterity' => 15,
                    'constitution' => 9,
                    'intelligence' => 8,
                    'wisdom' => 7,
                    'charisma' => 8,
                ],
                'speed' => ['walk' => 9],
                'saving_throws' => [],
                'skills' => [],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 8],
                'languages' => ['Общий', 'Драконий'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Чувствительность к солнечному свету',
                        'description' => 'Находясь на солнечном свету, кобольд совершает с помехой броски атаки и проверки Мудрости (Внимательность), полагающиеся на зрение.',
                    ],
                    [
                        'name' => 'Тактика стаи',
                        'description' => 'Кобольд совершает с преимуществом броски атаки по существу, если в пределах 1,5 метра от этого существа находится дееспособный союзник кобольда.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Кинжал',
                        'type' => 'melee',
                        'attack_bonus' => 4,
                        'reach' => '1,5 м',
                        'damage' => '1d4+2 колющий',
                        'description' => 'Рукопашная атака оружием: +4 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 4 (1d4+2) колющего урона.',
                    ],
                    [
                        'name' => 'Праща',
                        'type' => 'ranged',
                        'attack_bonus' => 4,
                        'range' => '9/36 м',
                        'damage' => '1d4+2 дробящий',
                        'description' => 'Дальнобойная атака оружием: +4 к попаданию, дистанция 9/36 м, одна цель. Попадание: 4 (1d4+2) дробящего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 1,
            ],

            // GOBLIN (CR 1/4)
            [
                'slug' => 'goblin',
                'name' => ['ru' => 'Гоблин'],
                'description' => ['ru' => 'Гоблины — маленькие злобные гуманоиды с плоскими лицами, широкими носами и острыми зубами. Они живут в тёмных местах и нападают из засады.'],
                'size' => 'small',
                'type' => 'humanoid',
                'alignment' => 'нейтрально-злой',
                'armor_class' => 15,
                'armor_type' => 'кожаный доспех, щит',
                'hit_points' => 7,
                'hit_dice' => '2d6',
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'abilities' => [
                    'strength' => 8,
                    'dexterity' => 14,
                    'constitution' => 10,
                    'intelligence' => 10,
                    'wisdom' => 8,
                    'charisma' => 8,
                ],
                'speed' => ['walk' => 9],
                'saving_throws' => [],
                'skills' => ['stealth' => 6],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 9],
                'languages' => ['Общий', 'Гоблинский'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Проворный побег',
                        'description' => 'Гоблин может в каждый свой ход совершать бонусным действием Отход или Засаду.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Скимитар',
                        'type' => 'melee',
                        'attack_bonus' => 4,
                        'reach' => '1,5 м',
                        'damage' => '1d6+2 рубящий',
                        'description' => 'Рукопашная атака оружием: +4 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 5 (1d6+2) рубящего урона.',
                    ],
                    [
                        'name' => 'Короткий лук',
                        'type' => 'ranged',
                        'attack_bonus' => 4,
                        'range' => '24/96 м',
                        'damage' => '1d6+2 колющий',
                        'description' => 'Дальнобойная атака оружием: +4 к попаданию, дистанция 24/96 м, одна цель. Попадание: 5 (1d6+2) колющего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 2,
            ],

            // SKELETON (CR 1/4)
            [
                'slug' => 'skeleton',
                'name' => ['ru' => 'Скелет'],
                'description' => ['ru' => 'Скелеты возникают, когда некромант оживляет кости мертвеца. Они повинуются приказам своего создателя и атакуют всех, кого тот укажет.'],
                'size' => 'medium',
                'type' => 'undead',
                'alignment' => 'законно-злой',
                'armor_class' => 13,
                'armor_type' => 'обрывки доспеха',
                'hit_points' => 13,
                'hit_dice' => '2d8+4',
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'abilities' => [
                    'strength' => 10,
                    'dexterity' => 14,
                    'constitution' => 15,
                    'intelligence' => 6,
                    'wisdom' => 8,
                    'charisma' => 5,
                ],
                'speed' => ['walk' => 9],
                'saving_throws' => [],
                'skills' => [],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 9],
                'languages' => ['понимает языки, которые знал при жизни, но не говорит'],
                'damage_resistances' => [],
                'damage_immunities' => ['яд'],
                'damage_vulnerabilities' => ['дробящий'],
                'condition_immunities' => ['истощение', 'отравление'],
                'traits' => [],
                'actions' => [
                    [
                        'name' => 'Короткий меч',
                        'type' => 'melee',
                        'attack_bonus' => 4,
                        'reach' => '1,5 м',
                        'damage' => '1d6+2 колющий',
                        'description' => 'Рукопашная атака оружием: +4 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 5 (1d6+2) колющего урона.',
                    ],
                    [
                        'name' => 'Короткий лук',
                        'type' => 'ranged',
                        'attack_bonus' => 4,
                        'range' => '24/96 м',
                        'damage' => '1d6+2 колющий',
                        'description' => 'Дальнобойная атака оружием: +4 к попаданию, дистанция 24/96 м, одна цель. Попадание: 5 (1d6+2) колющего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 3,
            ],

            // ZOMBIE (CR 1/4)
            [
                'slug' => 'zombie',
                'name' => ['ru' => 'Зомби'],
                'description' => ['ru' => 'Зомби — ожившие трупы, движимые тёмной магией. Они медленны, но упорны, и представляют угрозу своей неутомимостью.'],
                'size' => 'medium',
                'type' => 'undead',
                'alignment' => 'нейтрально-злой',
                'armor_class' => 8,
                'armor_type' => null,
                'hit_points' => 22,
                'hit_dice' => '3d8+9',
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'abilities' => [
                    'strength' => 13,
                    'dexterity' => 6,
                    'constitution' => 16,
                    'intelligence' => 3,
                    'wisdom' => 6,
                    'charisma' => 5,
                ],
                'speed' => ['walk' => 6],
                'saving_throws' => ['wisdom' => 0],
                'skills' => [],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 8],
                'languages' => ['понимает языки, которые знал при жизни, но не говорит'],
                'damage_resistances' => [],
                'damage_immunities' => ['яд'],
                'damage_vulnerabilities' => [],
                'condition_immunities' => ['отравление'],
                'traits' => [
                    [
                        'name' => 'Неживая стойкость',
                        'description' => 'Если урон уменьшает хиты зомби до 0, он должен совершить спасбросок Телосложения со Сл, равной 5 + полученный урон, если только урон не был излучением или от критического удара. При успехе хиты зомби уменьшаются до 1.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Удар',
                        'type' => 'melee',
                        'attack_bonus' => 3,
                        'reach' => '1,5 м',
                        'damage' => '1d6+1 дробящий',
                        'description' => 'Рукопашная атака оружием: +3 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 4 (1d6+1) дробящего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 4,
            ],

            // WOLF (CR 1/4)
            [
                'slug' => 'wolf',
                'name' => ['ru' => 'Волк'],
                'description' => ['ru' => 'Волки — свирепые хищники, охотящиеся стаями. Они известны своей хитростью и способностью координировать атаки.'],
                'size' => 'medium',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 13,
                'armor_type' => 'природный доспех',
                'hit_points' => 11,
                'hit_dice' => '2d8+2',
                'challenge_rating' => 0.25,
                'experience_points' => 50,
                'abilities' => [
                    'strength' => 12,
                    'dexterity' => 15,
                    'constitution' => 12,
                    'intelligence' => 3,
                    'wisdom' => 12,
                    'charisma' => 6,
                ],
                'speed' => ['walk' => 12],
                'saving_throws' => [],
                'skills' => ['perception' => 3, 'stealth' => 4],
                'senses' => ['passive_perception' => 13],
                'languages' => [],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Тонкий нюх',
                        'description' => 'Волк совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.',
                    ],
                    [
                        'name' => 'Тактика стаи',
                        'description' => 'Волк совершает с преимуществом броски атаки по существу, если в пределах 1,5 метра от этого существа находится дееспособный союзник волка.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Укус',
                        'type' => 'melee',
                        'attack_bonus' => 4,
                        'reach' => '1,5 м',
                        'damage' => '2d4+2 колющий',
                        'description' => 'Рукопашная атака оружием: +4 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 7 (2d4+2) колющего урона. Если цель — существо, она должна преуспеть в спасброске Силы Сл 11, иначе будет сбита с ног.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 5,
            ],

            // HOBGOBLIN (CR 1/2)
            [
                'slug' => 'hobgoblin',
                'name' => ['ru' => 'Хобгоблин'],
                'description' => ['ru' => 'Хобгоблины — крупные и воинственные гоблиноиды с дисциплинированным военным обществом. Они превосходные тактики и опасные противники.'],
                'size' => 'medium',
                'type' => 'humanoid',
                'alignment' => 'законно-злой',
                'armor_class' => 18,
                'armor_type' => 'кольчуга, щит',
                'hit_points' => 11,
                'hit_dice' => '2d8+2',
                'challenge_rating' => 0.5,
                'experience_points' => 100,
                'abilities' => [
                    'strength' => 13,
                    'dexterity' => 12,
                    'constitution' => 12,
                    'intelligence' => 10,
                    'wisdom' => 10,
                    'charisma' => 9,
                ],
                'speed' => ['walk' => 9],
                'saving_throws' => [],
                'skills' => [],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 10],
                'languages' => ['Общий', 'Гоблинский'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Воинское преимущество',
                        'description' => 'Один раз в ход хобгоблин может причинить дополнительные 7 (2d6) урона существу, по которому он попал атакой оружием, если это существо находится в пределах 1,5 метров от союзника хобгоблина, и тот союзник дееспособен.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Длинный меч',
                        'type' => 'melee',
                        'attack_bonus' => 3,
                        'reach' => '1,5 м',
                        'damage' => '1d8+1 рубящий',
                        'description' => 'Рукопашная атака оружием: +3 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 5 (1d8+1) рубящего урона, или 6 (1d10+1) рубящего урона, если используется двумя руками.',
                    ],
                    [
                        'name' => 'Длинный лук',
                        'type' => 'ranged',
                        'attack_bonus' => 3,
                        'range' => '45/180 м',
                        'damage' => '1d8+1 колющий',
                        'description' => 'Дальнобойная атака оружием: +3 к попаданию, дистанция 45/180 м, одна цель. Попадание: 5 (1d8+1) колющего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 6,
            ],

            // ORC (CR 1/2)
            [
                'slug' => 'orc',
                'name' => ['ru' => 'Орк'],
                'description' => ['ru' => 'Орки — свирепые гуманоиды с серо-зелёной кожей, выступающими клыками и мощным телосложением. Они живут войной и разрушением.'],
                'size' => 'medium',
                'type' => 'humanoid',
                'alignment' => 'хаотично-злой',
                'armor_class' => 13,
                'armor_type' => 'шкурный доспех',
                'hit_points' => 15,
                'hit_dice' => '2d8+6',
                'challenge_rating' => 0.5,
                'experience_points' => 100,
                'abilities' => [
                    'strength' => 16,
                    'dexterity' => 12,
                    'constitution' => 16,
                    'intelligence' => 7,
                    'wisdom' => 11,
                    'charisma' => 10,
                ],
                'speed' => ['walk' => 9],
                'saving_throws' => [],
                'skills' => ['intimidation' => 2],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 10],
                'languages' => ['Общий', 'Орочий'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Агрессия',
                        'description' => 'Бонусным действием орк может переместиться на расстояние до своей скорости к враждебному существу, которое он видит.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Большой топор',
                        'type' => 'melee',
                        'attack_bonus' => 5,
                        'reach' => '1,5 м',
                        'damage' => '1d12+3 рубящий',
                        'description' => 'Рукопашная атака оружием: +5 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 9 (1d12+3) рубящего урона.',
                    ],
                    [
                        'name' => 'Метательное копьё',
                        'type' => 'ranged',
                        'attack_bonus' => 5,
                        'range' => '9/36 м',
                        'damage' => '1d6+3 колющий',
                        'description' => 'Рукопашная или дальнобойная атака оружием: +5 к попаданию, досягаемость 1,5 м или дистанция 9/36 м, одна цель. Попадание: 6 (1d6+3) колющего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 7,
            ],

            // ==========================================
            // MEDIUM CR (1 - 4)
            // ==========================================

            // GIANT SPIDER (CR 1)
            [
                'slug' => 'giant-spider',
                'name' => ['ru' => 'Гигантский паук'],
                'description' => ['ru' => 'Гигантские пауки устраивают сложные сети в тёмных лесах и подземельях. Их ядовитый укус может парализовать жертву.'],
                'size' => 'large',
                'type' => 'beast',
                'alignment' => 'без мировоззрения',
                'armor_class' => 14,
                'armor_type' => 'природный доспех',
                'hit_points' => 26,
                'hit_dice' => '4d10+4',
                'challenge_rating' => 1,
                'experience_points' => 200,
                'abilities' => [
                    'strength' => 14,
                    'dexterity' => 16,
                    'constitution' => 12,
                    'intelligence' => 2,
                    'wisdom' => 11,
                    'charisma' => 4,
                ],
                'speed' => ['walk' => 9, 'climb' => 9],
                'saving_throws' => [],
                'skills' => ['stealth' => 7],
                'senses' => ['blindsight' => '3 м', 'darkvision' => '18 м', 'passive_perception' => 10],
                'languages' => [],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Паутинное передвижение',
                        'description' => 'Паук игнорирует ограничения перемещения, создаваемые паутиной.',
                    ],
                    [
                        'name' => 'Чувство паутины',
                        'description' => 'Находясь в контакте с паутиной, паук знает точное положение любого другого существа, контактирующего с той же паутиной.',
                    ],
                    [
                        'name' => 'Паутинный ходок',
                        'description' => 'Паук игнорирует ограничения перемещения, создаваемые паутиной.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Укус',
                        'type' => 'melee',
                        'attack_bonus' => 5,
                        'reach' => '1,5 м',
                        'damage' => '1d8+3 колющий + 2d8 яд',
                        'description' => 'Рукопашная атака оружием: +5 к попаданию, досягаемость 1,5 м, одно существо. Попадание: 7 (1d8+3) колющего урона, и цель должна совершить спасбросок Телосложения Сл 11, получая 9 (2d8) урона ядом при провале или половину этого урона при успехе. Если урон ядом уменьшает хиты цели до 0, цель стабилизируется, но отравлена на 1 час, даже после восстановления хитов, и парализована, пока отравлена таким образом.',
                    ],
                    [
                        'name' => 'Паутина',
                        'type' => 'ranged',
                        'attack_bonus' => 5,
                        'range' => '9/18 м',
                        'damage' => null,
                        'recharge' => '5-6',
                        'description' => 'Дальнобойная атака оружием: +5 к попаданию, дистанция 9/18 м, одно существо. Попадание: Цель опутана паутиной. Действием опутанная цель может совершить проверку Силы Сл 12, освобождаясь при успехе. Паутину можно атаковать и уничтожить (КД 10; хп 5; уязвимость к урону огнём; иммунитет к дробящему, психическому и урону ядом).',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 10,
            ],

            // OGRE (CR 2)
            [
                'slug' => 'ogre',
                'name' => ['ru' => 'Огр'],
                'description' => ['ru' => 'Огры — огромные, тупые гуманоиды, известные своей жестокостью и ненасытным голодом. Они часто служат более умным злым существам.'],
                'size' => 'large',
                'type' => 'giant',
                'alignment' => 'хаотично-злой',
                'armor_class' => 11,
                'armor_type' => 'шкурный доспех',
                'hit_points' => 59,
                'hit_dice' => '7d10+21',
                'challenge_rating' => 2,
                'experience_points' => 450,
                'abilities' => [
                    'strength' => 19,
                    'dexterity' => 8,
                    'constitution' => 16,
                    'intelligence' => 5,
                    'wisdom' => 7,
                    'charisma' => 7,
                ],
                'speed' => ['walk' => 12],
                'saving_throws' => [],
                'skills' => [],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 8],
                'languages' => ['Общий', 'Великаний'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [],
                'actions' => [
                    [
                        'name' => 'Палица',
                        'type' => 'melee',
                        'attack_bonus' => 6,
                        'reach' => '1,5 м',
                        'damage' => '2d8+4 дробящий',
                        'description' => 'Рукопашная атака оружием: +6 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 13 (2d8+4) дробящего урона.',
                    ],
                    [
                        'name' => 'Метательное копьё',
                        'type' => 'ranged',
                        'attack_bonus' => 6,
                        'range' => '9/36 м',
                        'damage' => '2d6+4 колющий',
                        'description' => 'Рукопашная или дальнобойная атака оружием: +6 к попаданию, досягаемость 1,5 м или дистанция 9/36 м, одна цель. Попадание: 11 (2d6+4) колющего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 12,
            ],

            // MINOTAUR (CR 3)
            [
                'slug' => 'minotaur',
                'name' => ['ru' => 'Минотавр'],
                'description' => ['ru' => 'Минотавры — свирепые чудовища с телом человека и головой быка. Они живут в лабиринтах и охотятся на тех, кто осмелится войти.'],
                'size' => 'large',
                'type' => 'monstrosity',
                'alignment' => 'хаотично-злой',
                'armor_class' => 14,
                'armor_type' => 'природный доспех',
                'hit_points' => 76,
                'hit_dice' => '9d10+27',
                'challenge_rating' => 3,
                'experience_points' => 700,
                'abilities' => [
                    'strength' => 18,
                    'dexterity' => 11,
                    'constitution' => 16,
                    'intelligence' => 6,
                    'wisdom' => 16,
                    'charisma' => 9,
                ],
                'speed' => ['walk' => 12],
                'saving_throws' => [],
                'skills' => ['perception' => 7],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 17],
                'languages' => ['Бездны'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Атака с разбега',
                        'description' => 'Если минотавр перемещается как минимум на 3 метра по прямой к цели и затем попадает по ней атакой боданием в тот же ход, цель получает дополнительно 9 (2d8) колющего урона. Если цель — существо, оно должно преуспеть в спасброске Силы Сл 14, иначе будет оттолкнуто на расстояние до 3 метров и сбито с ног.',
                    ],
                    [
                        'name' => 'Безошибочный навигатор',
                        'description' => 'Минотавр идеально помнит любой путь, который проходил.',
                    ],
                    [
                        'name' => 'Безрассудство',
                        'description' => 'В начале своего хода минотавр может получить преимущество на все броски рукопашных атак оружием, которые он совершает в течение этого хода, но броски атаки по нему тоже совершаются с преимуществом до начала его следующего хода.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Большой топор',
                        'type' => 'melee',
                        'attack_bonus' => 6,
                        'reach' => '1,5 м',
                        'damage' => '2d12+4 рубящий',
                        'description' => 'Рукопашная атака оружием: +6 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 17 (2d12+4) рубящего урона.',
                    ],
                    [
                        'name' => 'Бодание',
                        'type' => 'melee',
                        'attack_bonus' => 6,
                        'reach' => '1,5 м',
                        'damage' => '2d8+4 колющий',
                        'description' => 'Рукопашная атака оружием: +6 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 13 (2d8+4) колющего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 15,
            ],

            // OWLBEAR (CR 3)
            [
                'slug' => 'owlbear',
                'name' => ['ru' => 'Совомедведь'],
                'description' => ['ru' => 'Совомедведь — чудовищный гибрид с телом медведя и головой гигантской совы. Это свирепый хищник, нападающий на всё живое на своей территории.'],
                'size' => 'large',
                'type' => 'monstrosity',
                'alignment' => 'без мировоззрения',
                'armor_class' => 13,
                'armor_type' => 'природный доспех',
                'hit_points' => 59,
                'hit_dice' => '7d10+21',
                'challenge_rating' => 3,
                'experience_points' => 700,
                'abilities' => [
                    'strength' => 20,
                    'dexterity' => 12,
                    'constitution' => 17,
                    'intelligence' => 3,
                    'wisdom' => 12,
                    'charisma' => 7,
                ],
                'speed' => ['walk' => 12],
                'saving_throws' => [],
                'skills' => ['perception' => 3],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 13],
                'languages' => [],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Тонкое зрение и обоняние',
                        'description' => 'Совомедведь совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на зрение или обоняние.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Мультиатака',
                        'type' => 'special',
                        'description' => 'Совомедведь совершает две атаки: одну клювом и одну когтями.',
                    ],
                    [
                        'name' => 'Клюв',
                        'type' => 'melee',
                        'attack_bonus' => 7,
                        'reach' => '1,5 м',
                        'damage' => '1d10+5 колющий',
                        'description' => 'Рукопашная атака оружием: +7 к попаданию, досягаемость 1,5 м, одно существо. Попадание: 10 (1d10+5) колющего урона.',
                    ],
                    [
                        'name' => 'Когти',
                        'type' => 'melee',
                        'attack_bonus' => 7,
                        'reach' => '1,5 м',
                        'damage' => '2d8+5 рубящий',
                        'description' => 'Рукопашная атака оружием: +7 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 14 (2d8+5) рубящего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 16,
            ],

            // ==========================================
            // HIGH CR (5+)
            // ==========================================

            // TROLL (CR 5)
            [
                'slug' => 'troll',
                'name' => ['ru' => 'Тролль'],
                'description' => ['ru' => 'Тролли — длинные, тощие великаны с регенеративными способностями. Только огонь или кислота могут помешать их плоти восстанавливаться.'],
                'size' => 'large',
                'type' => 'giant',
                'alignment' => 'хаотично-злой',
                'armor_class' => 15,
                'armor_type' => 'природный доспех',
                'hit_points' => 84,
                'hit_dice' => '8d10+40',
                'challenge_rating' => 5,
                'experience_points' => 1800,
                'abilities' => [
                    'strength' => 18,
                    'dexterity' => 13,
                    'constitution' => 20,
                    'intelligence' => 7,
                    'wisdom' => 9,
                    'charisma' => 7,
                ],
                'speed' => ['walk' => 9],
                'saving_throws' => [],
                'skills' => ['perception' => 2],
                'senses' => ['darkvision' => '18 м', 'passive_perception' => 12],
                'languages' => ['Великаний'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Тонкий нюх',
                        'description' => 'Тролль совершает с преимуществом проверки Мудрости (Внимательность), полагающиеся на обоняние.',
                    ],
                    [
                        'name' => 'Регенерация',
                        'description' => 'Тролль восстанавливает 10 хитов в начале своего хода. Если тролль получает урон кислотой или огнём, эта особенность не работает в начале следующего хода тролля. Тролль умирает только если начинает свой ход с 0 хитами и не может регенерировать.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Мультиатака',
                        'type' => 'special',
                        'description' => 'Тролль совершает три атаки: одну укусом и две когтями.',
                    ],
                    [
                        'name' => 'Укус',
                        'type' => 'melee',
                        'attack_bonus' => 7,
                        'reach' => '1,5 м',
                        'damage' => '1d6+4 колющий',
                        'description' => 'Рукопашная атака оружием: +7 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 7 (1d6+4) колющего урона.',
                    ],
                    [
                        'name' => 'Когти',
                        'type' => 'melee',
                        'attack_bonus' => 7,
                        'reach' => '1,5 м',
                        'damage' => '2d6+4 рубящий',
                        'description' => 'Рукопашная атака оружием: +7 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 11 (2d6+4) рубящего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 20,
            ],

            // HILL GIANT (CR 5)
            [
                'slug' => 'hill-giant',
                'name' => ['ru' => 'Холмовой великан'],
                'description' => ['ru' => 'Холмовые великаны — тупые, прожорливые существа, которые живут ради еды. Они часто нападают на поселения в поисках скота и провизии.'],
                'size' => 'huge',
                'type' => 'giant',
                'alignment' => 'хаотично-злой',
                'armor_class' => 13,
                'armor_type' => 'природный доспех',
                'hit_points' => 105,
                'hit_dice' => '10d12+40',
                'challenge_rating' => 5,
                'experience_points' => 1800,
                'abilities' => [
                    'strength' => 21,
                    'dexterity' => 8,
                    'constitution' => 19,
                    'intelligence' => 5,
                    'wisdom' => 9,
                    'charisma' => 6,
                ],
                'speed' => ['walk' => 12],
                'saving_throws' => [],
                'skills' => ['perception' => 2],
                'senses' => ['passive_perception' => 12],
                'languages' => ['Великаний'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [],
                'actions' => [
                    [
                        'name' => 'Мультиатака',
                        'type' => 'special',
                        'description' => 'Великан совершает две атаки палицей.',
                    ],
                    [
                        'name' => 'Палица',
                        'type' => 'melee',
                        'attack_bonus' => 8,
                        'reach' => '3 м',
                        'damage' => '3d8+5 дробящий',
                        'description' => 'Рукопашная атака оружием: +8 к попаданию, досягаемость 3 м, одна цель. Попадание: 18 (3d8+5) дробящего урона.',
                    ],
                    [
                        'name' => 'Камень',
                        'type' => 'ranged',
                        'attack_bonus' => 8,
                        'range' => '18/72 м',
                        'damage' => '3d10+5 дробящий',
                        'description' => 'Дальнобойная атака оружием: +8 к попаданию, дистанция 18/72 м, одна цель. Попадание: 21 (3d10+5) дробящего урона.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 21,
            ],

            // YOUNG GREEN DRAGON (CR 8)
            [
                'slug' => 'young-green-dragon',
                'name' => ['ru' => 'Молодой зелёный дракон'],
                'description' => ['ru' => 'Зелёные драконы — хитрые манипуляторы, предпочитающие обман грубой силе. Они обитают в древних лесах и используют ядовитое дыхание.'],
                'size' => 'large',
                'type' => 'dragon',
                'alignment' => 'законно-злой',
                'armor_class' => 18,
                'armor_type' => 'природный доспех',
                'hit_points' => 136,
                'hit_dice' => '16d10+48',
                'challenge_rating' => 8,
                'experience_points' => 3900,
                'abilities' => [
                    'strength' => 19,
                    'dexterity' => 12,
                    'constitution' => 17,
                    'intelligence' => 16,
                    'wisdom' => 13,
                    'charisma' => 15,
                ],
                'speed' => ['walk' => 12, 'fly' => 24, 'swim' => 12],
                'saving_throws' => ['dexterity' => 4, 'constitution' => 6, 'wisdom' => 4, 'charisma' => 5],
                'skills' => ['deception' => 5, 'perception' => 7, 'stealth' => 4],
                'senses' => ['blindsight' => '9 м', 'darkvision' => '36 м', 'passive_perception' => 17],
                'languages' => ['Общий', 'Драконий'],
                'damage_resistances' => [],
                'damage_immunities' => ['яд'],
                'damage_vulnerabilities' => [],
                'condition_immunities' => ['отравление'],
                'traits' => [
                    [
                        'name' => 'Амфибия',
                        'description' => 'Дракон может дышать воздухом и водой.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Мультиатака',
                        'type' => 'special',
                        'description' => 'Дракон совершает три атаки: одну укусом и две когтями.',
                    ],
                    [
                        'name' => 'Укус',
                        'type' => 'melee',
                        'attack_bonus' => 7,
                        'reach' => '3 м',
                        'damage' => '2d10+4 колющий + 2d6 яд',
                        'description' => 'Рукопашная атака оружием: +7 к попаданию, досягаемость 3 м, одна цель. Попадание: 15 (2d10+4) колющего урона плюс 7 (2d6) урона ядом.',
                    ],
                    [
                        'name' => 'Когти',
                        'type' => 'melee',
                        'attack_bonus' => 7,
                        'reach' => '1,5 м',
                        'damage' => '2d6+4 рубящий',
                        'description' => 'Рукопашная атака оружием: +7 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 11 (2d6+4) рубящего урона.',
                    ],
                    [
                        'name' => 'Ядовитое дыхание',
                        'type' => 'special',
                        'recharge' => '5-6',
                        'description' => 'Дракон выдыхает ядовитый газ 9-метровым конусом. Все существа в этой области должны совершить спасбросок Телосложения Сл 14, получая 42 (12d6) урона ядом при провале или половину этого урона при успехе.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 30,
            ],

            // ADULT RED DRAGON (CR 17)
            [
                'slug' => 'adult-red-dragon',
                'name' => ['ru' => 'Взрослый красный дракон'],
                'description' => ['ru' => 'Красные драконы — самые жадные и тщеславные из хроматических драконов. Они живут в вулканических регионах и собирают огромные сокровищницы.'],
                'size' => 'huge',
                'type' => 'dragon',
                'alignment' => 'хаотично-злой',
                'armor_class' => 19,
                'armor_type' => 'природный доспех',
                'hit_points' => 256,
                'hit_dice' => '19d12+133',
                'challenge_rating' => 17,
                'experience_points' => 18000,
                'abilities' => [
                    'strength' => 27,
                    'dexterity' => 10,
                    'constitution' => 25,
                    'intelligence' => 16,
                    'wisdom' => 13,
                    'charisma' => 21,
                ],
                'speed' => ['walk' => 12, 'fly' => 24, 'climb' => 12],
                'saving_throws' => ['dexterity' => 6, 'constitution' => 13, 'wisdom' => 7, 'charisma' => 11],
                'skills' => ['perception' => 13, 'stealth' => 6],
                'senses' => ['blindsight' => '18 м', 'darkvision' => '36 м', 'passive_perception' => 23],
                'languages' => ['Общий', 'Драконий'],
                'damage_resistances' => [],
                'damage_immunities' => ['огонь'],
                'damage_vulnerabilities' => [],
                'condition_immunities' => [],
                'traits' => [
                    [
                        'name' => 'Легендарное сопротивление (3/день)',
                        'description' => 'Если дракон проваливает спасбросок, он может вместо этого сделать его успешным.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Мультиатака',
                        'type' => 'special',
                        'description' => 'Дракон может использовать своё Ужасающее присутствие. Затем он совершает три атаки: одну укусом и две когтями.',
                    ],
                    [
                        'name' => 'Укус',
                        'type' => 'melee',
                        'attack_bonus' => 14,
                        'reach' => '3 м',
                        'damage' => '2d10+8 колющий + 2d6 огонь',
                        'description' => 'Рукопашная атака оружием: +14 к попаданию, досягаемость 3 м, одна цель. Попадание: 19 (2d10+8) колющего урона плюс 7 (2d6) урона огнём.',
                    ],
                    [
                        'name' => 'Когти',
                        'type' => 'melee',
                        'attack_bonus' => 14,
                        'reach' => '1,5 м',
                        'damage' => '2d6+8 рубящий',
                        'description' => 'Рукопашная атака оружием: +14 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 15 (2d6+8) рубящего урона.',
                    ],
                    [
                        'name' => 'Хвост',
                        'type' => 'melee',
                        'attack_bonus' => 14,
                        'reach' => '4,5 м',
                        'damage' => '2d8+8 дробящий',
                        'description' => 'Рукопашная атака оружием: +14 к попаданию, досягаемость 4,5 м, одна цель. Попадание: 17 (2d8+8) дробящего урона.',
                    ],
                    [
                        'name' => 'Ужасающее присутствие',
                        'type' => 'special',
                        'description' => 'Все существа по выбору дракона, находящиеся в пределах 36 метров от него и знающие о его присутствии, должны преуспеть в спасброске Мудрости Сл 19, иначе станут испуганными на 1 минуту. Существо может повторять спасбросок в конце каждого своего хода, оканчивая эффект на себе при успехе. Если спасбросок существа был успешным, или эффект на нём окончился, это существо получает иммунитет к Ужасающему присутствию этого дракона на следующие 24 часа.',
                    ],
                    [
                        'name' => 'Огненное дыхание',
                        'type' => 'special',
                        'recharge' => '5-6',
                        'description' => 'Дракон выдыхает огонь 18-метровым конусом. Все существа в этой области должны совершить спасбросок Ловкости Сл 21, получая 63 (18d6) урона огнём при провале или половину этого урона при успехе.',
                    ],
                ],
                'legendary_actions' => [
                    'per_round' => 3,
                    'description' => 'Дракон может совершить 3 легендарных действия, выбирая из представленных ниже вариантов. За один раз можно использовать только одно легендарное действие, и только в конце хода другого существа. Дракон восстанавливает использованные легендарные действия в начале своего хода.',
                    'actions' => [
                        [
                            'name' => 'Обнаружение',
                            'cost' => 1,
                            'description' => 'Дракон совершает проверку Мудрости (Внимательность).',
                        ],
                        [
                            'name' => 'Атака хвостом',
                            'cost' => 1,
                            'description' => 'Дракон совершает атаку хвостом.',
                        ],
                        [
                            'name' => 'Атака крыльями (стоит 2 действия)',
                            'cost' => 2,
                            'description' => 'Дракон бьёт крыльями. Все существа в пределах 3 метров от дракона должны преуспеть в спасброске Ловкости Сл 22, иначе получат 15 (2d6+8) дробящего урона и будут сбиты с ног. После этого дракон может переместиться на расстояние до половины своей скорости полёта.',
                        ],
                    ],
                ],
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 50,
            ],

            // BEHOLDER (CR 13) - Iconic D&D monster
            [
                'slug' => 'beholder',
                'name' => ['ru' => 'Бехолдер'],
                'description' => ['ru' => 'Бехолдер — один из самых странных и опасных обитателей подземелий. Это парящая сфера плоти с огромным центральным глазом и множеством глазных стебельков, каждый из которых испускает смертоносный луч.'],
                'size' => 'large',
                'type' => 'aberration',
                'alignment' => 'законно-злой',
                'armor_class' => 18,
                'armor_type' => 'природный доспех',
                'hit_points' => 180,
                'hit_dice' => '19d10+76',
                'challenge_rating' => 13,
                'experience_points' => 10000,
                'abilities' => [
                    'strength' => 10,
                    'dexterity' => 14,
                    'constitution' => 18,
                    'intelligence' => 17,
                    'wisdom' => 15,
                    'charisma' => 17,
                ],
                'speed' => ['walk' => 0, 'fly' => 6],
                'saving_throws' => ['intelligence' => 8, 'wisdom' => 7, 'charisma' => 8],
                'skills' => ['perception' => 12],
                'senses' => ['darkvision' => '36 м', 'passive_perception' => 22],
                'languages' => ['Глубинная речь', 'Подземный'],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => ['сбивание с ног'],
                'traits' => [
                    [
                        'name' => 'Антимагический конус',
                        'description' => 'Центральный глаз бехолдера создаёт область антимагии, как заклинание преграда магии, в 45-метровом конусе. В начале каждого своего хода бехолдер решает, в какую сторону направлен конус и активен ли он. Область работает против собственных глазных лучей бехолдера.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Укус',
                        'type' => 'melee',
                        'attack_bonus' => 5,
                        'reach' => '1,5 м',
                        'damage' => '4d6 колющий',
                        'description' => 'Рукопашная атака оружием: +5 к попаданию, досягаемость 1,5 м, одна цель. Попадание: 14 (4d6) колющего урона.',
                    ],
                    [
                        'name' => 'Глазные лучи',
                        'type' => 'special',
                        'description' => 'Бехолдер стреляет тремя магическими глазными лучами, случайно выбранными из десяти возможных (перебрасывайте повторы), в одну-три цели, видимые в пределах 36 метров. Каждый луч имеет свой эффект (очарование, паралич, страх, замедление, телекинез, сон, окаменение, дезинтеграция, смерть, и т.д.).',
                    ],
                ],
                'legendary_actions' => [
                    'per_round' => 3,
                    'description' => 'Бехолдер может совершить 3 легендарных действия, используя только вариант Глазной луч (один луч). Он может использовать только одно легендарное действие за раз, и только в конце хода другого существа.',
                    'actions' => [
                        [
                            'name' => 'Глазной луч',
                            'cost' => 1,
                            'description' => 'Бехолдер использует один случайный глазной луч.',
                        ],
                    ],
                ],
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 45,
            ],

            // GELATINOUS CUBE (CR 2) - Classic dungeon hazard
            [
                'slug' => 'gelatinous-cube',
                'name' => ['ru' => 'Желатиновый куб'],
                'description' => ['ru' => 'Желатиновые кубы — это огромные, почти прозрачные слизи кубической формы, которые медленно ползают по подземельям, поглощая всё на своём пути.'],
                'size' => 'large',
                'type' => 'ooze',
                'alignment' => 'без мировоззрения',
                'armor_class' => 6,
                'armor_type' => null,
                'hit_points' => 84,
                'hit_dice' => '8d10+40',
                'challenge_rating' => 2,
                'experience_points' => 450,
                'abilities' => [
                    'strength' => 14,
                    'dexterity' => 3,
                    'constitution' => 20,
                    'intelligence' => 1,
                    'wisdom' => 6,
                    'charisma' => 1,
                ],
                'speed' => ['walk' => 5],
                'saving_throws' => [],
                'skills' => [],
                'senses' => ['blindsight' => '18 м (слеп за пределами этого радиуса)', 'passive_perception' => 8],
                'languages' => [],
                'damage_resistances' => [],
                'damage_immunities' => [],
                'damage_vulnerabilities' => [],
                'condition_immunities' => ['глухота', 'истощение', 'испуг', 'сбивание с ног', 'слепота', 'очарование'],
                'traits' => [
                    [
                        'name' => 'Форма слизи',
                        'description' => 'Куб может перемещаться сквозь пространство шириной не менее 2,5 см без протискивания.',
                    ],
                    [
                        'name' => 'Прозрачность',
                        'description' => 'Даже когда куб на виду, требуется успешная проверка Мудрости (Внимательность) Сл 15, чтобы заметить куб, который ещё не атаковал. Существо, которое пытается войти в пространство куба, не зная о нём, застаётся кубом врасплох.',
                    ],
                ],
                'actions' => [
                    [
                        'name' => 'Псевдопод',
                        'type' => 'melee',
                        'attack_bonus' => 4,
                        'reach' => '1,5 м',
                        'damage' => '3d6 кислота',
                        'description' => 'Рукопашная атака оружием: +4 к попаданию, досягаемость 1,5 м, одно существо. Попадание: 10 (3d6) урона кислотой.',
                    ],
                    [
                        'name' => 'Поглощение',
                        'type' => 'special',
                        'description' => 'Куб перемещается на расстояние до своей скорости. При этом он может входить в пространства существ Большого и меньшего размера. Когда куб входит в пространство существа, это существо должно совершить спасбросок Ловкости Сл 12. При успехе существо может использовать реакцию, чтобы отойти на 1,5 метра от куба. Существо, которое не отошло, поглощается кубом. Поглощённое существо не может дышать, опутано, и получает 21 (6d6) урона кислотой в начале каждого хода куба. Существо может попытаться выбраться, совершив проверку Силы Сл 12.',
                    ],
                ],
                'legendary_actions' => null,
                'lair_actions' => null,
                'regional_effects' => null,
                'is_system' => true,
                'sort_order' => 13,
            ],
        ];
    }
}
